- aperturedb/BlobLoader.py
- aperturedb/DescriptorLoader.py
- aperturedb/ImageLoader.py
- aperturedb/ParallelLoader.py
- aperturedb/VideoLoader.py
> Fix ImageLoader Error handling for missing images

- aperturedb/CSVParser.py
- aperturedb/ImageDownloader.py
- test/download_images.py
> Update Image downloader

- aperturedb/Utils.py
Needed for a customer workflow.
> Add method to retrieve uids for images

- aperturedb/QueryGenerator.py
This just adds a simple interface for generators, instead of having to inherit from the rather obscure "Subscriptable" class.
We are creating a good amount of code that inherits from Subscriptable, which we should change as soon as possible. 
This is one proposal, but not sure what is the right way of doing it.
> Add QueryGenerator class

- aperturedb/__init__.py
- setup.py
- test/aperturedb/config.json
This is to merge the changes back into develop.
> Release 0.2.4

- aperturedb/Utils.py
- test/conftest.py
- test/test_Data.py
- test/test_Loaders.py
- test/test_Utils.py
- test/test_torch_connector.py
This requires ApertureDB support for:
```
{"constraints": {"_uniqueid": ["!=", "0.0.0"]}}
```
> Add method to remove everything from db

- docs/requirements-documentation.txt
not sure why this failed the first time.
> Addressing a dependabot_alert.

- .github/workflows/main.yml
- aperturedb/__init__.py
- setup.py
removed deployment to k8, as it was blocking CI.
> rebasing dev to main.

- aperturedb/BBoxDataCSV.py
- aperturedb/ConnectionDataCSV.py
- aperturedb/ParallelQuery.py
When error returned from query was a dict, it was not getting handled.
> Random improvements.

- aperturedb/Connector.py
- aperturedb/__init__.py
- ci.sh
- setup.py
- test/conftest.py
- test/test_Session.py
- test/test_torch_connector.py
- Preserving the descriptor distance order for images when doing a similarity search
- Working around a Pandas annotation gotcha for Connection Data columns with same names
- Explicitly specifying the unique constraints for the case of ingestion of Bounding boxes and Connections.
- Logging of error, where status is not 0 or -1
> Release 0.3.3

- aperturedb/ParallelLoader.py
- aperturedb/ParallelQuery.py
- aperturedb/Parallelizer.py
- test/test_Stats.py
> Fixes on stats

- aperturedb/Images.py
- aperturedb/Videos.py
Applicable, when training, and few passes over datasets is involved.
> Slight optimization, when multilple iterations.

- .github/workflows/main.yml
- .github/workflows/pr.yaml
- .github/workflows/release.yaml
- .gitignore
- aperturedb/Connector.py
- aperturedb/__init__.py
- ci.sh
- docker/pytorch-gpu/Dockerfile
- docker/pytorch-gpu/build.sh
- docker/pytorch-gpu/scripts/start.sh
- setup.py
- test/run_test_container.sh
- Reconnect on connection drop during a long running connection.
- Tests on python conda env with python 3.7
> Release 0.4.0

- aperturedb/__init__.py
- setup.py
Changelog
- model based ingestion
> Release 0.4.3

- aperturedb/CSVParser.py
- aperturedb/DaskManager.py
- aperturedb/ParallelQuery.py
- setup.py
- test/conftest.py
- test/test_Data.py
- test/test_Datawizard.py
This resolves the CI failures since the release of pandas 2.0.0
> Remove the pin on dask.

- aperturedb/CSVParser.py
- aperturedb/ConnectionDataCSV.py
- aperturedb/Images.py
- aperturedb/ParallelQuery.py
- aperturedb/Subscriptable.py
- aperturedb/__init__.py
- setup.py
- test/conftest.py
- test/docker-compose.yml
This release puts in a explicit parameter for not fetching blobs when ingesting connections.
Other than that it has a flag in generator that can be used to fail on a user response handler.
> Release 0.4.6

- .github/workflows/main.yml
Used a wrong workflow ID previously.
> Triggering push in demos on release.

- aperturedb/Connector.py
- test/test_Server.py
> Provide better exception for user when server cannot even return Authentication

- .gitignore
- aperturedb/BBoxDataCSV.py
- aperturedb/BlobDataCSV.py
- aperturedb/BlobNewestDataCSV.py
- aperturedb/CSVParser.py
- aperturedb/ConnectionDataCSV.py
- aperturedb/DaskManager.py
- aperturedb/DescriptorDataCSV.py
- aperturedb/DescriptorSetDataCSV.py
- aperturedb/EntityDataCSV.py
- aperturedb/EntityUpdateDataCSV.py
- aperturedb/ImageDataCSV.py
- aperturedb/PolygonDataCSV.py
- aperturedb/SparseAddingDataCSV.py
- aperturedb/Subscriptable.py
- aperturedb/VideoDataCSV.py
- aperturedb/cli/ingest.py
- test/conftest.py
- test/dbinfo.py
- test/generateInput.py
- test/test_Stats.py
Also clean up a bunch of pass through parameters.
> Overridable flag to use blob baths relative to CSVs.

- .github/workflows/main.yml
- github-release.sh
Updates the github release API
Triggers the docs rebuild workflow on release.
> Refresh docs on release.

- README.md
- aperturedb/ParallelQuery.py
- examples/README.md
- examples/loaders_101/loaders.ipynb
I found some links to the old documentation structure.
> fix documentation links

- .github/workflows/pr.yaml
- aperturedb/ParallelLoader.py
- aperturedb/ParallelQuery.py
- aperturedb/Utils.py
- ci.sh
- test/run_test_container.sh
- test/test_Parallel.py
> Fix ParallelQuery assumptions on errors

- .github/workflows/pr.yaml
- aperturedb/Images.py
- aperturedb/NotebookHelpers.py
Changing the notebook helper to show similar output. To show that native queries and Images class can display similar looking images.
> Enabling axis on the plotlib show

- .github/workflows/pr.yaml
- aperturedb/Images.py
- aperturedb/NotebookHelpers.py
- aperturedb/ParallelLoader.py
- aperturedb/ParallelQuery.py
- aperturedb/Utils.py
- aperturedb/__init__.py
- ci.sh
- test/run_test_container.sh
- test/test_Parallel.py
- Images and helper sligns the outcome of multiple displays.
- Connector handles some responses from server more robustly.
- CI drops the validation on pytorch GPU image.
> Release 0.4.14

- docker/notebook/Dockerfile
- docker/notebook/scripts/start.sh
This change allow us to pass the jupyter lab password thru env variable:
https://github.com/aperture-data/infra/pull/380
> Set Jupyter Lab password thru ENV

- ci.sh
Line 221 had an unquoted variable that caused parse error.
> Bugfix unquoted variable

- pyproject.toml
> Updating the python packaging to include opencv dependency.

- aperturedb/cli/utilities.py
```
remis@server:~/ad/aperturedb$ adb config create yfcc
Enter aperturedb host name [localhost]: yfcc100m.datasets.gcp.aperturedata.io
Enter aperturedb port number [55555]:
Enter aperturedb username [admin]:
Enter aperturedb password [admin]:
Use REST [y/N]: N
Use SSL [Y/n]: Y
remis@server:~/ad/aperturedb$ adb config activate yfcc --as-global
remis@server:~/ad/aperturedb$ adb utils execute status
[
{
"GetStatus": {
"info": "OK",
"status": 0,
"system": "ApertureDB",
"version": "0.16.4"
}
}
]
```
> Add status to cli

- aperturedb/cli/utilities.py
makes some adb utils non interactive, to be used in scripts.
> force option for prompt.

- aperturedb/__init__.py
> Release 0.4.18

- aperturedb/BBoxDataCSV.py
- aperturedb/BlobDataCSV.py
- aperturedb/BlobNewestDataCSV.py
- aperturedb/CSVParser.py
- aperturedb/Configuration.py
- aperturedb/ConnectionDataCSV.py
- aperturedb/Connector.py
- aperturedb/ConnectorRest.py
- aperturedb/DaskManager.py
- aperturedb/DescriptorDataCSV.py
- aperturedb/DescriptorSetDataCSV.py
- aperturedb/Entities.py
- aperturedb/EntityDataCSV.py
- aperturedb/EntityUpdateDataCSV.py
- aperturedb/ImageDataCSV.py
- aperturedb/Images.py
- aperturedb/KaggleData.py
- aperturedb/NotebookHelpers.py
- aperturedb/ParallelLoader.py
- aperturedb/ParallelQuery.py
- aperturedb/Parallelizer.py
- aperturedb/PolygonDataCSV.py
- aperturedb/Polygons.py
- aperturedb/PyTorchDataset.py
- aperturedb/Query.py
- aperturedb/Stats.py
- aperturedb/VideoDataCSV.py
- test/conftest.py
- test/test_Parallel.py
Figured from here:
https://github.com/aperture-data/docs/actions/runs/7831429956/job/21367740358
> Fixing typos in the comments, and some code.

- aperturedb/Utils.py
- aperturedb/cli/utilities.py
Add Utils method for calling `UserLogmessage` with corresponding command in adb.
```
adb utils log "Hello world" --level WARNING
```
> Add log to adb

- aperturedb/Connector.py
- aperturedb/Images.py
- aperturedb/Utils.py
- aperturedb/cli/utilities.py
I'm not done here (Is documentation ever done?), but I wanted to get something out for people to review.
One question: Should I be trying to hyperlink more in Python documentation?
Note: This documentation change also includes a small bugfix for `Images.rotate` that affects the mapping of bboxes when images are resized to a non-square.
> Documentation improvements for docker release

- aperturedb/Images.py
This follows the change at the server side.
> Explicitly specify blobs in FindImages.

- aperturedb/BBoxDataCSV.py
- aperturedb/BlobDataCSV.py
- aperturedb/BlobNewestDataCSV.py
- aperturedb/CSVParser.py
- aperturedb/ConnectionDataCSV.py
- aperturedb/DescriptorDataCSV.py
- aperturedb/DescriptorSetDataCSV.py
- aperturedb/EntityDataCSV.py
- aperturedb/EntityUpdateDataCSV.py
- aperturedb/ImageDataCSV.py
- aperturedb/Images.py
- aperturedb/ParallelLoader.py
- aperturedb/ParallelQuery.py
- aperturedb/ParallelQuerySet.py
- aperturedb/Parallelizer.py
- aperturedb/PolygonDataCSV.py
- aperturedb/SparseAddingDataCSV.py
- aperturedb/Utils.py
- aperturedb/VideoDataCSV.py
- aperturedb/__init__.py
- aperturedb/cli/utilities.py
- aperturedb/types.py
- deploy/main.tf
- test/conftest.py
Has couple of bug fixes:
1. FindImage in Images explicitly sets blobs.
2. fps in Video helper was hardcoded, and now is based on source fps.
> Release 0.4.22

- aperturedb/cli/ingest.py
This would have failed for datasets with no id property.
Tested when running for celebA DS with 2 descriptor sets.
> Better ids for connections between images and descriptors

- aperturedb/Connector.py
- aperturedb/Polygons.py
- aperturedb/Utils.py
- test/docker-compose.yml
This would result in a warn log when trying to connect for the first time, which is not really a case for warning.
> Do not log first connection attempt.

- aperturedb/Descriptors.py
- aperturedb/EntityUpdateDataCSV.py
- aperturedb/ParallelLoader.py
Simple descriptors wrapper that just provides `find_similar`and `find_similar_mmr` to use in langchain.
> Descriptors wrapper

- aperturedb/Connector.py
Related: https://github.com/aperture-data/athena/issues/1525
> Add warning for message size larger than 256MB

- pyproject.toml
Unpin versions of pytorch and tf
> unpin ml lib versions.

- aperturedb/__init__.py
> Release 0.4.29

- .pre-commit-config.yaml
- aperturedb/ParallelQuery.py
- aperturedb/ParallelQuerySet.py
- aperturedb/Utils.py
- test/test_ResponseHandler.py
It's optional, we wrap in ParallelQuery at beginning of loop.
> Add 'index' parameter for response_handler

- .pre-commit-config.yaml
- aperturedb/Descriptors.py
- aperturedb/ParallelQuery.py
- aperturedb/ParallelQuerySet.py
- aperturedb/Utils.py
- aperturedb/__init__.py
- test/test_ResponseHandler.py
Has changes to support LangChain integration.
> Release 0.4.30

- aperturedb/Utils.py
The `adb config` does not easily support having multiple connectors with different configurations in the same application (except by messing around with the environment variables).  This change allows the user to specify an explicit configuration name.  I have also tidied up the code, guarded against missing data, and made the documentation clearer.
> Support named config in create_connector

- README.md
- aperturedb/cli/README.md
- aperturedb/cli/ingest.py
- aperturedb/cli/transact.py
- aperturedb/cli/utilities.py
- test/adb_timing_tests.py
- test/run_test.sh
Addresses part of #467 .
adb config * run under 0.5 seconds.
> Reordered imports to lazily import them .Makes CLI snappier.

- aperturedb/BBoxDataCSV.py
- aperturedb/ConnectionDataCSV.py
- aperturedb/Connector.py
- aperturedb/ConnectorRest.py
- aperturedb/DescriptorSetDataCSV.py
- aperturedb/EntityDataCSV.py
- aperturedb/ImageDataCSV.py
- aperturedb/ImageDownloader.py
- aperturedb/ParallelQuery.py
- aperturedb/ParallelQuerySet.py
- aperturedb/ProgressBar.py
- aperturedb/Utils.py
- aperturedb/cli/configure.py
- aperturedb/types.py
using ssl from adb config.
fixes some points of #467
> Removing non essential imports, timeouts, and overwrite confirmation

- aperturedb/Query.py
- aperturedb/QueryTypes.py
- examples/loading_with_models/add_video_model.py
- pyproject.toml
Also, some clean up in requiring python min to 3.8
> https url in pydantic models, and specifying the lowest version of supported python

- examples/image_classification/pytorch_classification.ipynb
> MInor fix for new paths in docs

- aperturedb/CSVWriter.py
This only covers entities, images, and connections.  Should be extended to other types.
No tests yet for this functionality.
This functionality is not yet exposed in CLI.
> Adding CSV helper functions

- aperturedb/__init__.py
> Release 0.4.33

- aperturedb/CommonLibrary.py
This PR has two changes:
* In the specific case of being in a Google Colab environment but not being in a notebook, we will not crash when attempting to access secrets.
* When using a connection from a Google Colab secret, we will automatically create and activate a config called "google_colab".
> Handle colab non-notebook; auto-create config from colab secret

- aperturedb/CommonLibrary.py
- aperturedb/__init__.py
- aperturedb/cli/configure.py
- examples/image_classification/pytorch_classification.ipynb
has the updated config create feature.
> Release 0.4.34

- aperturedb/Connector.py
- test/test_ResponseHandler.py
This is the reason why there was no logging on non zero response on Create index when the index already exists scenario.
> Fix bug on check_status

- aperturedb/Connector.py
- aperturedb/__init__.py
- aperturedb/cli/transact.py
- test/test_ResponseHandler.py
> Release 0.4.35

- aperturedb/CommonLibrary.py
- aperturedb/cli/configure.py
In this morning's meeting, we wanted the user to be able to manage multiple cloud instances, using a name specified in the cloud UI to distinguish them.  In order to support this, we need the name argument to `adb config create` to be optional, which has a number of consequences.
> Make name optional, add better error handling, and a little helpful output

- aperturedb/cli/configure.py
- test/test_CLI.py
I added some tests for `--from-json` and I found and fixed a bug with the new functionality.
> Fix bug and add tests

- .gitignore
- README.md
- aperturedb/Entities.py
- aperturedb/Images.py
- aperturedb/Query.py
- aperturedb/SPARQL.py
- aperturedb/__init__.py
- aperturedb/transformers/clip_pytorch_embeddings.py
- aperturedb/transformers/common_properties.py
- aperturedb/transformers/facenet_pytorch_embeddings.py
- aperturedb/transformers/image_properties.py
- aperturedb/transformers/transformer.py
- pyproject.toml
- test/conftest.py
- test/pytest.ini
- test/test_SPARQL.py
Following new features available in this release:
- Brings in the SPARQL wrapper.
- Frame abstraction in the SDK.
> Release 0.4.37

- aperturedb/__init__.py
- aperturedb/transformers/clip_pytorch_embeddings.py
- aperturedb/transformers/facenet_pytorch_embeddings.py
Adds a if not found on transformer artifacts.
> Release 0.4.40

- aperturedb/ConnectionDataCSV.py
This extra param is no longer needed at the server
> Removing unneccessary code

- test/run_test.sh
If need be, they will be present on s3 bucket.
> Removing the excess log on stdout for CI

- aperturedb/ParallelLoader.py
- aperturedb/Utils.py
> Refactor and clean up.

- aperturedb/SPARQL.py
I noticed that the blobs aren't been ordered according to the input list.
> Fix sparql blob order

- aperturedb/CommonLibrary.py
- aperturedb/ConnectionDataCSV.py
- aperturedb/ConnectorRest.py
- aperturedb/ParallelLoader.py
- aperturedb/SPARQL.py
- aperturedb/Sources.py
- aperturedb/Utils.py
- aperturedb/__init__.py
- aperturedb/cli/ingest.py
- aperturedb/cli/transact.py
- docker/notebook/scripts/start.sh
- test/docker-compose.yml
- test/run_test.sh
- test/test_UserConvenience.py
Brings small improvements and bug fixes.
> Release 0.4.41

- aperturedb/Utils.py
- aperturedb/transformers/clip_pytorch_embeddings.py
Use CS in CLIP embeddings, as it works the best.
> Change defaults to HNSW and Cosine similarity

- aperturedb/Utils.py
- aperturedb/__init__.py
- aperturedb/transformers/clip_pytorch_embeddings.py
Unblocks usage in Windows platform.
Also has a change in default metrics and engine in DescriptorSet creation.
> Release 0.4.44

- pyproject.toml
Removing unnecessary dependencies.
> Remove old dependencies.

- .gitignore
- ci.sh
- test/docker-compose.yml
- test/run_test.sh
- test/run_test_container.sh
This run_test completed in 40 mins.
> Improve run time by running http and non http tests concurrently

- .github/workflows/checks.yml
- .github/workflows/develop.yml
- .github/workflows/main.yml
- .github/workflows/pr.yaml
- .gitignore
- README.md
- aperturedb/CommonLibrary.py
- aperturedb/Configuration.py
- aperturedb/Connector.py
- aperturedb/Utils.py
- aperturedb/__init__.py
- aperturedb/cli/adb.py
- aperturedb/cli/configure.py
- aperturedb/cli/keys.py
- aperturedb/cli/tokens.py
- aperturedb/cli/utilities.py
- ci.sh
- test/.env
- test/adb_timing_tests.py
- test/docker-compose.yml
- test/run_test.sh
- test/run_test_container.sh
Introduces APERTUREDB_KEY as a way to authenticate.
> Release 0.4.46

- aperturedb/Configuration.py
- aperturedb/Connector.py
- aperturedb/ConnectorRest.py
- aperturedb/cli/keys.py
- test/test_Key.py
Changes the APERTUREDB_KEY format to a unified format with the cloud.
* Changes format to v1 spec from 2025-06-02
* Fixes some bugs related to cloning configurations which use keys
> Unified APERTUREDB_KEY with Cloud

- aperturedb/cli/configure.py
* Removes 1 configuration
* can operate at global or local
* refuses to remove active config unless given options.
* can either take a config to set active, or can just assign one.
> Add 'remove' for configurations

- aperturedb/MLCroissant.py
- aperturedb/cli/ingest.py
1. example of getting a URL ingested as a blob.
2. option of flattening a json into connected entities (1 level)
3. Has no intermediate conversion into a Dataframe
> Croissant data enrichment
