aperture-data/aperturedb-python

aperturedb/ConnectionLoader.py

Report user errors when unexpected or incorrect keys are used in Loader.
When Generator uses keys other than the ones expected by the Loader (e.g. `ref1_value` instead of `ref1_val`), the author of the Generator would get a detailed error message.

try_catch_user_input

---

aperturedb/ConnectionLoader.py

Bug/omission fix
We use `sys` module without imprting it. Require when an error happens.

ConnectionLoader_py_fix

---

.github/workflows/main.yml
configure_deployment.sh
deploy/aperturedb-python-cc-deployment.yaml
deploy/aperturedb-python-docs-deployment.yaml

Since we do not maintain a 'latest' image in the ECR. We'll specify the tag from the release being created.

Set tag before kubectl apply.

---

aperturedb/Images.py

A few minor changes in support of COCO demo.
The only breaking change is to replace `Images.search_by_id()` with `Images.search_by_property()` (I think this only affects [the COCO polygon demo PR](https://github.com/aperture-data/demos/pull/40))

Minor improvements to Images.py

---

aperturedb/BBoxDataCSV.py
aperturedb/BlobDataCSV.py
aperturedb/CSVParser.py
aperturedb/ConnectionDataCSV.py
aperturedb/DescriptorDataCSV.py
aperturedb/DescriptorSetDataCSV.py
aperturedb/EntityDataCSV.py
aperturedb/ImageDataCSV.py
aperturedb/ParallelLoader.py
aperturedb/ParallelQuery.py
aperturedb/Parallelizer.py
aperturedb/PolygonDataCSV.py
aperturedb/VideoDataCSV.py
test/conftest.py
test/run_test_container.sh

When using data loaders, it will attempt to create an index for any property we use for conditional add (ie. with `constraint_` prefix), if it is not already indexed.
Fixes #136

autogenerate indices using parallel loader

---

docs/docker/Dockerfile

This is causing [CI failure](https://github.com/aperture-data/aperturedb-python/actions/runs/5139222602/jobs/9249429931).

updating docs builder to ubuntu 22

---

aperturedb/Images.py

There was an API change on ApertureDB that no longer accepts `ids` as parameter of FindDescriptor.

Fix get_similar_images on Images.py

---

aperturedb/CSVParser.py
aperturedb/ConnectionDataCSV.py
aperturedb/ParallelQuery.py
aperturedb/Subscriptable.py
test/conftest.py
test/docker-compose.yml

1. This flag ensures that a failure in response handler terminates ingestion, and any behavior changes in aperturedb or python lib will be automatically caught.
2. There is a specific override for ConnectionDataCSV, to ensure we set blobs = false for known objects like image video and blobs.

Introducing "strict_response_validation" in loader

---

test/docker-compose.yml

Removes the version pin that was introduced to work around https://github.com/aperture-data/athena/issues/1026

revert adb version pin

---

test/conftest.py
test/mark_checker.py
test/pytest.ini
test/test_Data.py
test/test_kaggle.py

- adds mark_checker which allows gating of imports based on what marks are selected
- adds some marks, and decorations
- uses mark_checker to disable kaggle import unless selected as example.

Add pytest marks and mark checker

---

aperturedb/Configuration.py
aperturedb/Connector.py
requirements.txt
setup.py

This PR adds (client-side) keepalive to `Connector`.  This uses a small third-party library that claims to work on Linux, MacOS, and Windows.  The new feature is enabled by default.
From my testing, queries longer than about five minutes will be disconnected on AWS (and probably on GCP too).  This problem affects `remove_all_objects`, but would also affect large batch imports.  With this new feature enables, I can keep a query running AWS->AWS for an hour without problems.
This feature does increate network traffic slightly, but the only reason I'm aware of to disable it is if you are accessing aperturedb over a cellular connection.  I am therefore enabling it by default.

Add keepalive

---

aperturedb/Configuration.py
aperturedb/Connector.py
test/conftest.py
test/docker-compose.yml
test/run_test_container.sh
test/test_Session.py

This would handle scenarios where a long running connection would be checked for errors, with logic to recover.
Reported as in #258

Re establish connection on errors.

---

aperturedb/BBoxDataCSV.py
aperturedb/ConnectionDataCSV.py
aperturedb/PolygonDataCSV.py

The aperturedb API permits refs to be in the range [1,100000), and uses higher numbers for internal purposes.  Because of a recent change in the aperturedb API, we are now enforcing this restriction, whereas previously violations were quietly ignored.  The CSV loader wants to avoid ref collision when batching, so assigns refs serially, modulo a limit.  Because these refs are sometimes assigned in pairs, we were going over this limit.  This change ensures we stay under the limit.
Note that there is still an outstanding problem because the CSV loader is merely hoping that this modulo trick is sufficient to ensure that batches are semantically coherent.  A better approach might be to have the batching process itself remap ref numbers on the fly.

Internal ref ids start at 10000

---

aperturedb/Images.py

Continue processing for the rest of images.

Do not raise an exception if BBox is not attached.

---

aperturedb/ParallelQuery.py
test/test_ResponseHandler.py

Currently, response_handler is not being passed the right blobs corresponding to the response. This Branch has a workaround that will pass the right blobs under the special condition that we have BATCH_SIZE=1, but there is a need for a more general fix. 
This branch is needed for `nsfw_detector` to work: https://github.com/aperture-data/demos/pull/148

Fix for response_handler

---

aperturedb/ConnectorRest.py

Some exceptions raised in http retry loop prevented retry to continue. I added exception handling to let retry finish its work.

Handle exceptions in retry loop

---

ci.sh

Despite the fact that we build and push the docker image every night, an older version of [cached dependencies](https://github.com/aperture-data/aperturedb-python/actions/runs/7939158216/job/21678899491) was being used to build aperturedb-notebook.

docker notebook should use the latest dependencies.

---

aperturedb/Connector.py

This method is crucial for writing multi-threaded applications.  A customer reported a problem this morning, and we are about to recommend that they fix it using this (previously-undocumented) method.

Document Connector.create_new_connection

---

aperturedb/NotebookHelpers.py

This was hardcoded previously.

Derive fps from the Video Capture.

---

aperturedb/PyTorchDataset.py

@gsaluja9 what do you think about this? 
This is another issue that is causing tests to fail, it seems: https://benchmarks.aperturedata.dev/view/adb-performance-evaluation/2024-03-20/trial_lab_test/1710960685_unspecified_app_run/app.log
It can be solved by this: https://github.com/aperture-data/demos/pull/194/files#diff-76485030a837ba5490fa41692f2fd95803c6002d3f2ea2dfbb58ca73d2993438R99 on the application side. 
But we may want to protect PyTorchDataset class against this error. Please test and merge or discard as you see fit.

Fix PytorchDataset

---

aperturedb/Utils.py
aperturedb/cli/utilities.py
pyproject.toml

This adds a `visualize_schema` method to `Utils` and a corresponding `visualize-schema` command to the CLI.
Simply call
```
adb utils visualize-schema
```
or 
```
adb utils visualize-schema --filename=schema --format=png
```
Relies on graphviz installation.

First pass at schema visualization

---

aperturedb/Utils.py

Colours changed and formatting tweaked.  
See https://github.com/aperture-data/aperturedb-python/pull/403 for before example.
After:

Change schema visualization colours to use website palette

---

.github/workflows/main.yml

There was an error  in referring to a branch that does not exist in docs repo. This PR fixes that.

Any changes leading up to a release should update docs.

---

aperturedb/ParallelQuery.py
aperturedb/cli/ingest.py
test/conftest.py
test/test_Server.py

This used to result in errors on the line of :
unhashable type: 'slice', which was not a useful (underlying) bit to be shown to the user.
For example, with a return code 3, the query or transaction does not return a list which was the earlier expectation in calculating the actual stats.

Do not assume an subscriptable of errors when commands fail at aperturedb

---

examples/CocoDataPyTorch.py

Ingestion command:
`adb ingest from-generator examples/CocoDataPyTorch.py  --sample-count 1 --transformer image_properties`
View the image(s) :
```
q=[
{
"FindImage": {
"blobs": True,
"uniqueids": True,
"unique": False,
"results": {
"limit": 5,
"all_properties": True
}
}
}
]
r, blobs = db.query(q, [])
imgs = Images(db, response=r[0]["FindImage"]["entities"])
imgs.display(show_polygons=True, show_bboxes=True)
```

Included segmentation info when ingesting coco annotations.

---

aperturedb/cli/transact.py
pyproject.toml

This will ensure that the user sees warning if they explicitly try to use mount in non compatible env.

More packaging fixes.

---

aperturedb/ParallelQuery.py
aperturedb/ParallelQuerySet.py
test/test_ResponseHandler.py

Move response_handler generation into ParallelQuery, simplyfing execute_batch.
Adds response_handler for ParallelQuerySet, defined as set_number,query,query_blobs,response,response_blobs.

Add response handler support to ParallelQuerySet

---

aperturedb/Utils.py

Adding optional properties parameter to `Utils.add_descriptorset`.  This is useful for clients that want to record information about the descriptorset.  I plan to use it in the langchain integration.

Add descriptorset properties

---

docker/dependencies/Dockerfile
pyproject.toml

numpy 2.0 creates incompatibility, and was released on Jun 16.
Pinning this till a better fix is available.

Pin numpy to less than 2.

---

aperturedb/Utils.py

I noticed during the Exthymic tech talk that the text for connection properties wasn't very readable.
Before:
After:

Make connection property font color darker

---

aperturedb/__init__.py
pyproject.toml

Google Colab sets up logging slightly differently from Jupyter.  Specifically it creates a `<StreamHandler stderr (NOTSET)>` handler on the root logger.  This means that if a library (like ours) sets the logger level to DEBUG, then it gets printed, regardless of the level on the handlers we set up.
With this change, we'll set the logger level to the minimum of the two handler levels if either is explicitly set.
This also includes a fix for an unrelated Kaggle problem. https://github.com/Kaggle/kaggle-api/issues/611

Colab logging

---

aperturedb/Connector.py
test/test_Session.py

Re authenticate when refresh token fails.

---

aperturedb/Images.py

When execution fails we get a spurious error of local variables not defined.

switch declaration order in images

---

aperturedb/CommonLibrary.py
aperturedb/cli/configure.py

[ Recreation of https://github.com/aperture-data/aperturedb-python/pull/501 with lower-case branch name ]
Part of a set of changes to optimize quick start, etc.
This change adds a --from-json option to adb config create. If specified, then the normal connection parameters are ignored and instead we look for a JSON string in one of three places:
The environment variable APERTUREDB_JSON
An entry for APERTUREDB_JSON in a .env file
In interactive mode, the user will be prompted to enter the JSON string. This is treated like a password.

Add --from-json to adb config create

---

aperturedb/cli/configure.py

After some discussion this morning, we decided that, while we do like the smart behaviour of `CommonLibrary.create_connector`, we want the CLI `adb config create --from-json` to be less smart.  With this change, it will not look at environment variables; it will not look in dotenv files; it will simply accept an interactive input and nothing else.
The name remains optional, and will override the name in the JSON if provided.
I closed a gap whereby names from JSON/interactive were not checked for overwrite.  We now check in three places:
* When the name is given on the command line
* When the name is inferred from the JSON file
* When the name is given interactively

Make `adb config create --from-json` dumber

---

aperturedb/Entities.py
aperturedb/Images.py
aperturedb/Query.py
test/conftest.py
test/pytest.ini

Modifies Images to support Frames, based on usage pattern from https://github.com/drewaogle/YOLOv4-OpenCV-CUDA-DNN/blob/main/VideoClips.ipynb which aimed to use `Images`, but on frame objects.

modify Images to support Frames as a subclass

---

aperturedb/Query.py

Accidentally used python 3.10 syntax: `def call( var : str | int )`

Fix Query parameter types for Python 3.9

---

docker/tests/Dockerfile
publish.sh
pyproject.toml

A recently undedected failure happened while publishing 0.4.37 https://github.com/aperture-data/aperturedb-python/actions/runs/11728588500/job/32675080673#step:6:555

pypi does not accept artifact with github based dependencies.

---

aperturedb/__init__.py

Fixes #544 
Simply removed ':' from default `now` filename substitution, removing the item win32 doesn't like in files.
@bovlb mentioned without the ':' is a valid iso date, this is slightly less user readable, but I don't think users are extremely concerned about reading

Fix logging on Win32

---

aperturedb/Sources.py

When downloading images or videos, sometimes content is not received completely and the `requests` library doesn't reflect any error. Comparing `Content-Length` header with the size of received content will tell us if content was downloaded completely or no.

Check content length of image matches the content-length header

---

aperturedb/CommonLibrary.py
aperturedb/__init__.py

- execute_query makes blobs optional.
- a faulthandler for imperatively getting a stack trace of a program

Miscellaneous usability features

---

aperturedb/cli/ingest.py

Removes the last 3 lines in the example below, which seem unnecessary on default logging configuration:
```
Progress: 100.00% - ETA(s): 0.00
============ ApertureDB Loader Stats ============
Total time (s): 134.3380880355835
Total queries executed: 1184
Avg Query time (s): 0.8870820974981463
Query time std: 0.18877949737167854
Avg Query Throughput (q/s): 9.018331023208049
Overall insertion throughput (element/s): 880.517221360692
Total inserted elements: 118287
Total successful commands: 354861
=================================================
adb ingest from-csv /app/input/train_images.adb.csv_clip_pytorch_embeddings_metadata.adb.csv --ingest-type DESCRIPTOR --batchsize 100 --num-workers 8 --no-use-dask --sample-count -1 --stats
[17:32:14] No transformer applied …
```

Remove debugging logs for cli ingest.py

---

.github/workflows/main.yml
docker/twine/Dockerfile
publish.sh

The agents for github runner runs as a non root user now. This can lead to problems where superuser privileges are expected. Adding sudo would have also worked, but it pollutes the shared environment.
This should unblock the release process which fails with the error like [this](https://github.com/aperture-data/aperturedb-python/actions/runs/13319411786/job/37203633059)

Run twine from container, without apt get.

---

.github/workflows/main.yml
aperturedb/__init__.py
docker/twine/Dockerfile
publish.sh

Run twine from container, without apt get. (#559)

---

aperturedb/cli/utilities.py

Fix #557 
```
❯ adb utils execute status
[
{
"GetStatus": {
"info": "OK",
"status": 0,
"system": "ApertureDB",
"version": "0.18.8"
}
}
]
```

Fix adb utils execute status

---

aperturedb/__init__.py

user on ApertureDB slack reported issue.
https://docs.python.org/3/library/faulthandler.html#dumping-the-traceback-on-a-user-signal
`register` is not available on windows; it will simply throw an error if you try to sue it.

Fix stacktrace invocation making import impossible in windows

---

pyproject.toml

it appears that grpcio-status was pinned to aid in installing `google-cloude-bigquery`
however now:
```
python3 -m venv ./bqtest
./bqtest/bin/activate
pip install -e .
pip install google-cloud-bigquery
```
works fine.
Results are:
```
(bq_test) drew@Dunstan:/code/aperture/aperturedb-python$ pip list | grep grpc
grpcio                   1.71.0
grpcio-status            1.71.0
```
versus old:
```
(adb_testing) drew@Dunstan:~$ pip list | grep grpc
grpcio                    1.63.0
grpcio-status             1.48.2
```
so it looks like a newer gprc can be used as well.

remove grpcio-status pin

---

.github/workflows/checks.yml

This unblocks all the failing CI runs.
Note the error message : https://github.com/aperture-data/aperturedb-python/actions/runs/14339506382/job/40195048106?pr=581

bump up pre commit version

---

aperturedb/CommonLibrary.py
aperturedb/Connector.py
aperturedb/ConnectorRest.py
aperturedb/EntityUpdateDataCSV.py
aperturedb/MLCroissant.py
aperturedb/cli/ingest.py
test/run_test.sh
test/test_CLI.py

This can be invoked as follows:
For a dry run (all the generated queries in files in cwd):
```
adb ingest from-croissant https://huggingface.co/api/datasets/FreedomIntelligence/PubMedVision/croissant --sample-count 1 --debug
adb ingest from-croissant https://huggingface.co/api/datasets/Rapidata/text-2-video-human-preferences-veo3/croissant --sample-count 1 --debug
adb ingest from-croissant https://huggingface.co/api/datasets/MathLLMs/MathVision/croissant --sample-count 1 --debug
```
Without the trailing --debug to actually run these queries on ApertureDB.
TODO:

Adds a class that can iterate over Croissant datasets and generate queries to persist them to ApertureDB.

---

aperturedb/Connector.py

Simplify parsing of options to Connector ( fixes a bug I had with passing in a key not setting use_keepalive )
adds documentation to say how it works.

Connector config unification
